### ISSUE TITLE
Cannot extend JacksonJsonProvider and implement an interface

### ISSUE THREAD

**Issue by rraziel** [FasterXML/jackson-jaxrs-providers#100]
Hello,

I'm not sure whether this is really a Jackson issue or a CXF issue, but here goes:
- I have a simple class - `MyJsonProvider` - that extends `JacksonJsonProvider` and passes an `ObjectMapper` through the constructor
- I then pass it to `JAXRSServerFactoryBean.setProviders()`

When doing this, I can use JSON just fine in my requests and responses.

Now, if I create an empty interface - `MyInterface` - and have `MyJsonProvider` extend `JacksonJsonProvider` and implement `MyInterface`, it seems the provider is completely ignored by CXF. As soon as I comment out the "implements MyInterface" part it works again.

Is this due to some specific JacksonJsonProvider internals or to the way CXF identifies providers? I also have a number of classes that implement ExceptionMapper and MyInterface, which are recognized just fine when passed to setProviders.

Thanks.

**Comment by cowtowncoder** [comment]
@mputters Jackson does not really use code generation for anything other than small pieces by optional `jackson-module-mrbean` and `jackson-module-afterburner`; and in those cases they just generate value (mr bean) and (de)serializer (afterburner) classes. So I don't think this is something that jackson jaxrs provider does.

**Comment by mputters** [comment]
So what you're saying is that the fact it's no longer used as a provider when I implement an empty interface is more likely a CXF issue?

**Comment by cowtowncoder** [comment]
@mputters Yes, I think so. I think many web frameworks (and others like Hibernate) use code generation for creating proxies and may not include things like annotations when doing that. I do not know what CXF does but it seems plausible they would be doing that too.

**Comment by rraziel** [comment]
Issue in CXF rather than jackson-jaxrs-provider
