### ISSUE TITLE
Plans for a 2.9.0.pr3 release

### ISSUE THREAD

**Issue by wilkinsona** [FasterXML/jackson-jaxrs-providers#101]
I noticed that 2.9.0.pr3 of the bom and many of the modules that it references are in Maven Central but the modules managed in this repository are not. Are there plans for a 2.9.0.pr3? The bom isn't very useful without it.

**Comment by cowtowncoder** [comment]
@wilkinsona This is just a by-product of slow release process; not to worry I'll get them all out. In fact, should be out by now.

**Comment by wilkinsona** [comment]
Thanks, @cowtowncoder. And sorry for the noise.
