### ISSUE TITLE
Undocumented XML serialization change introduced in Jackson 2.7.4 

### ISSUE THREAD

**Issue by sdjacobs** [FasterXML/jackson-jaxrs-providers#110]
While fixing issues in a project introduced by a Jackson upgrade, I found an undocumented change that was introduced in PR #81. I wanted to document this change in case it's useful to anyone else, or in case it hides a bug in Jackson that should be fixed.

Jackson 2.7.4 made it so classes with a `@XmlRootElement` annotation use wrapper tags around collection objects, and ignore Jackson annotations.

I created a minimal example here: https://github.com/sdjacobs/grizzly-jackson-example

Class `Customer` is defined as follows:

```java
@XmlRootElement(name = "customer")
public class Customer {

    private String name;

    private Map<String, String> properties;

    @JacksonXmlProperty(localName = "customName")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Map<String, String> getProperties() {
        return properties;
    }

    public void setProperties(Map<String, String> properties) {
        this.properties = properties;
    }
}
```

In Jackson version 2.7.3, `/myapp/myresource` returns:
```xml
<Customer>
  <properties>
    <status>ok</status>
  </properties>
  <customName>joe</customName>
</Customer>
```

In version 2.7.4 and the current version 2.9.8, it returns:
```xml
<customer>
  <name>joe</name>
  <properties>
    <entry>
      <key>status</key>
      <value>ok</value>
    </entry>
  </properties>
</customer>
```

Note that `@JacksonXmlProperty` is no longer respected and `Map.Entry` is wrapped in `key`, `value` tags.

The original behavior can be recreated by removing the `@XmlRootAnnotation` line. 

I narrowed down the code change that changes the behavior to:
https://github.com/FasterXML/jackson-jaxrs-providers/blob/ae4a06f4fdad4bd21ff251cb75fbae21d95f85fe/xml/src/main/java/com/fasterxml/jackson/jaxrs/xml/JacksonXMLProvider.java#L49

I get the original behavior if I change that line to: `@Produces({MediaType.TEXT_XML, MediaType.APPLICATION_XML})`

For my purposes, I've solved my problem, but that line change had broader implications in the system than I think it was intended to have! So I thought it may be helpful to report it.

**Comment by t2gran** [comment]
Thank you for this explanation, it was most helpful.

**Comment by cowtowncoder** [comment]
Hmmh. In hindsight, this should have only gone in 2.8.0, not in patch.

Another question is the wider impact on bindings and mappings.

**Comment by cowtowncoder** [comment]
Not quite sure if there is anything to do here, other than to note that changes like this really should not go in a patch release. And could use more discussion on mailing lists (although regrettably my experience is that participation on such questions is rather low -- people tend to report problems after the fact much more likely than actively check out proposed changes that they do not immediately recognize as being relevant).
And more generally we could use more JAX-RS expertise with this module, of course.

Will close now since I do not see actionable take aways.
