### ISSUE TITLE
Version 2.9.9 is missing in maven repos but stated in the bom

### ISSUE THREAD

**Issue by aspan** [FasterXML/jackson-jaxrs-providers#112]

**Comment by cowtowncoder** [comment]
Patience is a virtue... release process is not instantaneous.

**Comment by aspan** [comment]
Sorry didn’t realize. Keep up the good work!

**Comment by cowtowncoder** [comment]
@aspan Unfortunately it's a sort of side-effect: I need to update `bom` first, and only then proceed with publishing of other components. So it's understandable this looks like (and well, is) a problem.
Especially as the process of publishing takes about 2 hours full time, and sometimes more if there are any isses; on top which there is Maven Central latency.
