### ISSUE TITLE
2.10.1 kills JVM with "Exported package com.fasterxml.jackson.jaxrs.json already declared"

### ISSUE THREAD

**Issue by triceo** [FasterXML/jackson-jaxrs-providers#120]
When running an app with 2.10.1 using JPMS, I get the following error:

    Error occurred during initialization of boot layer
    java.lang.module.FindException: Error reading module: 
    /home/triceo/.m2/repository/com/fasterxml/jackson/jaxrs/jackson-jaxrs-json-provider/2.10.1/jackson-jaxrs-json-provider-2.10.1.jar
    Caused by: java.lang.module.InvalidModuleDescriptorException: Exported package com.fasterxml.jackson.jaxrs.json already declared

I am assuming this has to do with the following `module-info.class` that my IntelliJ IDEA decompiled for me:

![decompiled](https://user-images.githubusercontent.com/247403/68805599-72c17a00-0664-11ea-8c52-a7f7a36c1bfa.png)

(See lines 15 and 16.)

Unfortunately, this makes Jackson 2.10.1 unusable in the context of Java modularity.

**Comment by triceo** [comment]
FYI @cowtowncoder 
(#114 was fixed in 2.10.1, so I was able to proceed and find this one.)

**Comment by cowtowncoder** [comment]
Would this be fixed by this:

https://github.com/FasterXML/jackson-jaxrs-providers/pull/119

?

**Comment by cowtowncoder** [comment]
And yes, I was right from beginning. I FUCKING HATE Oracle's piece of shit module systems.

Was probably bad move to try to support it.

**Comment by triceo** [comment]
Is there a nightly build somewhere that I could try?

**Comment by cowtowncoder** [comment]
Sonatype OSS repo has some of the snapshots, but looks like Travis settings for this project have not been updated to build them (unlike core projects). I can do manual deploy from home tonight

**Comment by triceo** [comment]
@cowtowncoder That would be appreciated - I will test it then.

**Comment by paperlib** [comment]
Same error pops up when trying to list dependencies via jdeps:

```
$ jdeps --list-deps ./jackson-jaxrs-json-provider-2.10.1.jar
Exception in thread "main" java.lang.module.FindException:
  Error reading module: ./jackson-jaxrs-json-provider-2.10.1.jar
Caused by: java.lang.module.InvalidModuleDescriptorException:
  Exported package com.fasterxml.jackson.jaxrs.json already declared
```

full error dump:

```
$ jdeps --list-deps ./jackson-jaxrs-json-provider-2.10.1.jar
 Exception in thread "main" java.lang.module.FindException: Error reading module: ./jackson-jaxrs-json-provider-2.10.1.jar
	at java.base/jdk.internal.module.ModulePath.readModule(ModulePath.java:349)
	at java.base/jdk.internal.module.ModulePath.scan(ModulePath.java:236)
	at java.base/jdk.internal.module.ModulePath.scanNextEntry(ModulePath.java:189)
	at java.base/jdk.internal.module.ModulePath.findAll(ModulePath.java:165)
	at jdk.jdeps/com.sun.tools.jdeps.JdepsConfiguration$Builder.build(JdepsConfiguration.java:536)
	at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.buildConfig(JdepsTask.java:589)
	at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:543)
	at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:519)
	at jdk.jdeps/com.sun.tools.jdeps.Main.main(Main.java:49)
Caused by: java.lang.module.InvalidModuleDescriptorException: Exported package com.fasterxml.jackson.jaxrs.json already declared
	at java.base/jdk.internal.module.ModuleInfo.invalidModuleDescriptor(ModuleInfo.java:1092)
	at java.base/jdk.internal.module.ModuleInfo.read(ModuleInfo.java:134)
	at java.base/jdk.internal.module.ModulePath.readJar(ModulePath.java:651)
	at java.base/jdk.internal.module.ModulePath.readModule(ModulePath.java:330)
	... 8 more
```

**Comment by jflefebvre06** [comment]
Same problem

```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.119 s
[INFO] Finished at: 2019-11-20T12:07:51+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project ant-tasks: Execution default-compile of goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile failed: Exported package com.fasterxml.jackson.jaxrs.json already declared -> [Help 1]
```

**Comment by robinvanpraet** [comment]
It is causing issues on my side as well. I don't even know how you managed to compile this?!?
Please fix asap

**Comment by tomdw** [comment]
Same problem here, it is not the module system which is to blame. Just an invalid module-info with a duplicate export package. Please fix asap indeed, blocking.

**Comment by kupci** [comment]
@robinvanpraet @tomdw Knowing that nothing annoys cowtowncoder more than people ordering him what to do with his free time, I'm curious if you've considered subscribing for **Enterprise Support**, which looks like just the sort of thing to address these sorts of issues?

**Enterprise support**

_Available as part of the Tidelift Subscription.

The maintainers of jackson-jaxrs-providers and thousands of other packages are working with Tidelift to deliver commercial support and maintenance for the open source dependencies you use to build your applications. Save time, reduce risk, and improve code health, while paying the maintainers of the exact dependencies you use. Learn more._

**Comment by rolaca11** [comment]
This issue is fixed with the 2.11.0-SNAPSHOT version and 3.0.0-SNAPSHOT version. 

It's not ideal to use snapshots, but it seems to work nicely on my end

**Comment by cowtowncoder** [comment]
Yes, comments about "Fix this IMMEDIATELY" are annoying and frustrating. I literally do not work for any of you, nor do I take orders from you. I do however work with community members who will try to help; thank you everyone who has contributed in positive way.

As to fix this should be resolved in 2.10.2 as far as I know, and release should be forthcoming within a week or so. If anyone wants to help, verification with a build from `2.10` branch would be good idea, but if and when `2.11` works (as per @rolaca11 ) 2.10.2 should be good too.

**Comment by cowtowncoder** [comment]
2.10.2 now released.

**Comment by doctorpangloss** [comment]
I am now seeing the following error:

```
error: package com.fasterxml.jackson.jaxrs.json is not visible
import com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider;
                                  ^
  (package com.fasterxml.jackson.jaxrs.json is declared in module com.fasterxml.jackson.jaxrs.json, which does not export it)
```

This is resolved with the following compiler option:

```
--add-exports=com.fasterxml.jackson.jaxrs.json/com.fasterxml.jackson.jaxrs.json=my.module.name
```

```
module com.fasterxml.jackson.jaxrs.json {
  requires com.fasterxml.jackson.annotation;
  requires com.fasterxml.jackson.core;
  requires com.fasterxml.jackson.databind;
  requires com.fasterxml.jackson.module.jaxb;
  requires com.fasterxml.jackson.jaxrs.base;
  requires static javax.ws.rs.api;
  requires static java.ws.rs;
  requires static jakarta.ws.rs.api;

  exports com.fasterxml.jackson.jaxrs.json.annotation;

  opens com.fasterxml.jackson.jaxrs.json;

  provides javax.ws.rs.ext.MessageBodyReader with com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider;
  provides javax.ws.rs.ext.MessageBodyWriter with com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider;
}
```

I think you meant to `exports com.fasterxml.jackson.jaxrs.json` still, just not twice?

**Comment by rolaca11** [comment]
I had no problems with the new version, built my project without a problem and the Jax-RS application can send and receive JSON information with the Jackson Jax-RS provider. I also use Jackson annotations.

@doctorpangloss I'd suggest you post a question on StackOverflow, maybe even link it here. As far as I'm concerned, the issue is fixed.

**Comment by triceo** [comment]
I can confirm that my problem is fixed, and since I'm the original reporter, I'll close this one. If there is another problem uncovered by the fix, please file a new issue for it.

Thanks for the fix!

**Comment by cowtowncoder** [comment]
@triceo Thank you for confirming this. If there are new issues we'll try to tackle them; everyone's help in verification is appreciated given that I only run and build things on JDK 8 on regular basis.
I do have later jdks installed and occasionally do spot checks; pls Travis build is enabled for jdk 11, but in case of module system it does not give very deep coverage without integration tests by something else that uses module jars.

**Comment by robinvanpraet** [comment]
@cowtowncoder I confirm that we have the same issue as @doctorpangloss being that the com.fasterxml.jackson.jaxrs.json package is now not exported at all.
Not only is Swagger using the JacksonJsonProvider directly, Siren4J for example is extending it as well. As you can see here https://github.com/eserating/siren4j/blob/master/src/main/java/com/google/code/siren4j/jackson/MessageBodyWriterJSON.java

The workaround does work (but that's just a workaround), so the new release does help us out. Thanks!

@doctorpangloss did you create another issue for this?

**Comment by cowtowncoder** [comment]
@GedMarc just to make sure does this make sense? I can see that double export was now fully removed (perhaps due to merging fail) but wanted to make sure adding it makes sense since you are most familiar with testing for Module metadata.

**Comment by GedMarc** [comment]
@cowtowncoder Correct -
The base and jax-rs modules both had them.

With 2.10.2 out, I do need to update the JDK 11 Compat test libraries again to point to these instead of the standalone singles I used.

JAX-RS is included in the JDK 11 Compat 11 Test Suite, I do still however need to do the travis build for the JLink confirmation then that nut can be put to rest for all those modules.

**Comment by cowtowncoder** [comment]
@GedMarc @robinvanpraet Ok looking at `src/moditect/module-info.java` again, I _think_ the thing that confuses me is this: there is actually `opens` declaration:

```
module com.fasterxml.jackson.jaxrs.json {
    exports com.fasterxml.jackson.jaxrs.json.annotation;

    // 13-Nov-2019: [jaxrs-providers#119]: CXF, RESTEasy, OpenAPI require reflective access
    opens com.fasterxml.jackson.jaxrs.json;

    requires com.fasterxml.jackson.annotation;
    requires com.fasterxml.jackson.core;
    requires com.fasterxml.jackson.databind;
    requires com.fasterxml.jackson.module.jaxb;
....
```

which, being a more extensive access, would seem like implying "exports" as well.
But I guess not? So I just want to have a confirmation given that none of tools I use (maven build, IDE) complain about declarations even via dependencies, probably since they tend to run with more open (default?) access.

**Comment by GedMarc** [comment]
@cowtowncoder 

The opens clause is cause the consumers perform reflection on that package :)

Wellll!!! - The JDK 11 test is passing because in JDK 11, opens clause does indeed also mean exports.
JDK 12 and up, this is not the case, it needs to be exported as well

You don't wanna know what I went through to figure this one out.

**Comment by cowtowncoder** [comment]
Oh well. No wonder googling for the answer did not really bring up definite answers.... :)

But at least this helps further explain why it is possible for some users to have issues, others not, even with same or similar usage. I will add the export too, then.

**Comment by cowtowncoder** [comment]
Note: changed title a bit as I will use this issue number for fix inclusion in 2.10.3.
Thank you everyone for your help here.

**Comment by robinvanpraet** [comment]
@cowtowncoder thanks for the fix. Do you have an idea when you could release version 2.10.3? It would help me out a lot.

**Comment by cowtowncoder** [comment]
Unfortunately I just released 2.10.2 so it will be few months off.

One possibility would be micro-patch just for JAX-RS tho (2.10.2.1), wherein I only need to publish this repo?

**Comment by GedMarc** [comment]
@cowtowncoder please use this - it is 100% operational across all jdk's from what I can test (building on all jdk's sigh to ensure lol)

https://github.com/GedMarc/JWebMPDevKit/blob/master/GuicedEE/Services/jackson-jaxrs/src/moditect/module-info.java


base -- https://github.com/GedMarc/JWebMPDevKit/blob/master/GuicedEE/Services/jackson-jaxrs-base/src/moditect/module-info.java

@robinvanpraet Please can you check that this satisfies and provides the fix - 
https://search.maven.org/artifact/com.guicedee.services/jackson-jaxrs-json-provider

**Comment by cowtowncoder** [comment]
@GedMarc as far as I can see, these 2 are identical to what 2.11 branch has, so that should be good.

**Comment by tomdw** [comment]
@cowtowncoder A 2.10.2.1 release with this fix would also be great. And if it is a possibility, please prefer to release jackson as a whole to avoid needing to manage multiple version numbers for jackson libs.

**Comment by cowtowncoder** [comment]
Full release takes half a day so I do not have time to spend on that at this point.
But micro patch is doable. That's what those are for, and I can match that with `jackson-bom` that does provide full version set (even if there is but one difference).

**Comment by robinvanpraet** [comment]
@cowtowncoder any idea when this micro patch would be available? Thanks

**Comment by cowtowncoder** [comment]
I can release it tonight.

**Comment by cowtowncoder** [comment]
JAX-RS 2.10.2.1 released, on its way to Maven Central; matching `jackson-bom` has version `2.10.2.20200129`.

**Comment by cowtowncoder** [comment]
Update: looks like bom mentioned above is no good (accidentally defines dep versions as 2.10.3-SNAPSHOT): will push one with version `2.10.2.20200130`.
