### ISSUE TITLE
Sending iso format date in query param

### ISSUE THREAD

**Issue by beena-yatin-kanyal** [FasterXML/jackson-jaxrs-providers#122]
I have a functionality where the user is ending some dates like - `2019-10-29T12:07:12+0000, 2019-10-29T12:07:12+00:00` from the postman but at the connector side; Jackson automatically converts the plus (`+`) sign to space. Is there any way to escape this??

Some other details -
1. For timestamp using datatype as String.
2. Tried the use of `@Encoded` annotation with `@QueryParam`. It works but it messes the colon (`:`) in the timestamp.
`@QueryParam("start-date-time") @Encoded final String startDateTime`

Is there any way to retrieve the timestamp as it is sent by the user?

**Comment by cowtowncoder** [comment]
Ok, first things first: in future, please send usage questions to mailing list (https://groups.google.com/forum/#!forum/jackson-user) or Gitter chat room (https://gitter.im/FasterXML/jackson-databind).

But as to the issue: Jackson does not handle query parameters at all, as far as I know; frameworks typically handle that either using something else, or will need to implement some kind of conversion.
In latter case it would be necessary to know what exactly framework does.
So either way you would need to go through help for the framework in question.

Hope this helps.
