### ISSUE TITLE
Allow Jakarta Namespace Referencing

### ISSUE THREAD

**Issue by GedMarc** [FasterXML/jackson-jaxrs-providers#129]
When using Jakarta artifacts the below error is encountered in Module mode and in old classpath mode when used

```
Error occurred during initialization of boot layer
java.lang.module.ResolutionException: Module com.fasterxml.jackson.jaxrs.json does not read a module that exports javax.ws.rs.ext
```

The javax.ws.rs.ext package no longer exists, 

Refers to #125 and the recommended fix of shading a classified deployable artifact for Jakarta 

https://github.com/FasterXML/jackson-modules-base/pull/116

**Comment by cowtowncoder** [comment]
Is this still active, or possibly covered by other issues/PRs?
