### ISSUE TITLE
Remove work-around for JAX-RS 1.x wrt JAX-RS 2 type `NoContentException`

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-jaxrs-providers#134]
Looks like there is still a work-around to not require JAX-RS 2.x exception type `NoContentException` in codebase.
That seems unnecessary as dependency to JAX-RS 2.0 has been around for years now, so let's remove this kludge.

**Comment by pjfanning** [comment]
fyi - this causes issues for projects using jersey-core v1 and/or jsr311-api jar (Hadoop eco-system, for instance) - these are old and I'm not requesting for this change to be undone - the workaround is to use Jackson 2.12.6.1 or 2.12.7 (if you want CVE free jackson)

**Comment by cowtowncoder** [comment]
Thank you @pjfanning this is good to know. Might also mean that 2.12.x branch needs to be kept open bit longer than it otherwise would.
