### ISSUE TITLE
Publish 2.13.x version with woodstox:6.4.0 to fix CVEs

### ISSUE THREAD

**Issue by adriil** [FasterXML/jackson-jaxrs-providers#161]
Hi team,

Is there a plan to release a version with `woodstox-core:6.4.0` in the `2.13.x` line, similar to versions `2.13.4.1` and `2.13.4.2` published for `jackson-databind` ?

Thanks,
Adrien

**Comment by cowtowncoder** [comment]
Eventually yes (2.13.5), but I don't think I have time to do releases in near future. Instead I would recommend users to add explicit woodstox version overrides if they want to.

Also note, however, that the default configuration by XML provider is such that CVE is NOT APPLICABLE -- DTD handling is disabled.

**Comment by adriil** [comment]
Thank you very much for your quick answer, I didn’t know that the CVE doesn’t apply by default.
I‘ll check and if I finally need it I will override as suggested.

**Comment by cowtowncoder** [comment]
@adriil Yeah unfortunately a big portion of CVEs do not actually apply to many users -- so the whole cost of upgrades yields diminishing value. But then again figuring out if your system is affected is not trivial either; and maintaining overrides/exclusions for security scanners is work too.

**Comment by cowtowncoder** [comment]
I will close this, not because there won't be release but because there will eventually be -- I just need to get 2.14.0 completed first.
