### ISSUE TITLE
How to disable JaxRSFeature.READ_FULL_STREAM.

### ISSUE THREAD

**Issue by hkawa608** [FasterXML/jackson-jaxrs-providers#181]
Ref to: https://github.com/FasterXML/jackson-jaxrs-providers/issues/108

In Jesey 2.41, JaxRSFeature.READ_FULL_STREAM is set to true by default. Due to this change, we have an interoperability problem that we cannot fix or avoid. So we want to disable this feature by default.
How can we disable this feature?
I googled a lot, but I cannot find a solution...
We don't register any sub ProviderBase classes manually to ResourceConfig.

**Comment by pjfanning** [comment]
@hkawa608 why not report this to Jersey team. FasterXML/Jackson is not in any way affiliated with Jersey.

https://github.com/eclipse-ee4j/jersey

**Comment by hkawa608** [comment]
Exactly. I moved the issue to the Jersey repo.
Thanks!

**Comment by cowtowncoder** [comment]
Hmmh. Is this Jersey thing? `base/src/main/java/com/fasterxml/jackson/jaxrs/cfg/JaxRSFeature.java` is part of Jackson JAX-RS providers repo.

I suspect @hkawa608 meant "Jackson 2.15 changed defaults", not Jersey version (except perhaps indirectly if Jersey includes Jackson JAX-RS provider).

**Comment by hkawa608** [comment]
After I looked back at the code, it is in the Jersey repository. It imports Jackson's code into the Jersey repository. So this is Jersey thing.

https://github.com/eclipse-ee4j/jersey/commit/e79aa535afe6f2c9fb7b0a39e4d0cc02d198c99a#diff-2ef29e24080600307e208ebcf3399be243501ea767e94224d4923f1f95828eaeR489-R491

**Comment by cowtowncoder** [comment]
Ok thank you @hkawa608.

**Comment by cowtowncoder** [comment]
Wait a minute -- why are they literally copying Jackson source files? That is... not good.

**Comment by hkawa608** [comment]
Actually, they modify Jackson source files a bit. e.g. ProviderBase implements some Jersey interfaces.
https://github.com/eclipse-ee4j/jersey/blob/e79aa535afe6f2c9fb7b0a39e4d0cc02d198c99a/media/json-jackson/src/main/java/org/glassfish/jersey/jackson/internal/jackson/jaxrs/base/ProviderBase.java#L55-L58

**Comment by cowtowncoder** [comment]
Those are general JAX-RS interfaces, implemented in the original (except `Versioned` which comes from `jackson-core`).
But they do include references to where sources came from so technically it's not problematic. Just seems bit odd. Whatever.

**Comment by hkawa608** [comment]
Oh.. exactly.
I don't know why they copied the source files...
