### ISSUE TITLE
MavenGate (CVE)

### ISSUE THREAD

**Issue by amareshdlphx** [FasterXML/jackson-jaxrs-providers#182]
XFrog triggers an alert XRAY-589059 on packages:

- com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider
- com.fasterxml.jackson.jaxrs:jackson-jaxrs-base
- com.fasterxml.jackson.core:jackson-databind
- com.fasterxml.jackson.core:jackson-core
- com.fasterxml.jackson.core:jackson-annotations

Looks like domain name _com.fasterxml.jackson.jaxrs_ is not registered hence the groupId can be claimed by malicious user.

**Comment by cowtowncoder** [comment]
@amareshdlphx That is not true. `fasterxml.com` domain is registered by me; has been for years.
 Please do not spread FUD when you do not actually have information on subject.
You could -- for example -- have checked out web page served from http://fasterxml.com/ .
