### ISSUE TITLE
Provide a way to customize `ObjectReader` / `ObjectWriter` used by end points

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-jaxrs-providers#33]
(note: inspired by #32)

---

It would be nice to be able to customize configuration of `ObjectReader` used for reading content via JAX-RS, and configuration of `ObjectWriter` used for writing.
This functionality should be accessible from code outside of JAX-RS provider implementation.

**Comment by renaudcerrato** [comment]
How does that fit with the caching mechanisms? It seems the key used to cache the writer/reader is computed [from annotations and type](https://github.com/FasterXML/jackson-jaxrs-providers/blob/master/base/src/main/java/com/fasterxml/jackson/jaxrs/base/ProviderBase.java#L565).

**Comment by cowtowncoder** [comment]
@renaudcerrato It should work fine as information is passed using `ThreadLocal`; annotations are only used to create baseline `ObjectWriter` / `ObjectReader`, but then modifier can create new instances. Modification call is made on per-request basis. I hope test case shows how this occurs.
It all works as `ObjectReader`/`ObjectWriter` are immutable, so concurrent threads are not changing reader/writer instances but constructing new ones (with `withXxx()` methods), returning ones to use.
