### ISSUE TITLE
Support JAX-RS 2.0 in OSGi environment

### ISSUE THREAD

**Issue by marci74** [FasterXML/jackson-jaxrs-providers#37]
Hi,

tested with version 2.3.0 of Jackson-JAXRS-JSON:

The Import-Package statements in the manifest expect javax.ws.rs.\* with version [1.1.1,1.2) to be available. So version >= 2.0 does not work. Is it not supported? If I manually change the dependency it does work without any problems with Jersey 2 in my application.

**Comment by rsprit** [comment]
Is there any reason why the smile and cbor providers have not been updated in the same way to support the jax-rs 2.0 api in OSGI ?

**Comment by cowtowncoder** [comment]
@rsprit Just an oversight, or bad copy/paste. I'll create a follow-up issue.

**Comment by cowtowncoder** [comment]
Created #63 separate from this so it can be referenced from release notes.
