### ISSUE TITLE
Add support for javax.annotation.security data filtering

### ISSUE THREAD

**Issue by giovannibotta** [FasterXML/jackson-jaxrs-providers#45]
Jersey provides means to filter data based on user roles, which is something very useful when designing REST services. However, they don't support this feature for Jackson (besides, they are still using v 1.9). 

I was wondering if it was possible to add this as a provider feature. I know I could use `JsonView`s, but I feel like using standard annotations will turn out to be more portable.

**Comment by cowtowncoder** [comment]
Not sure what more to work on here at this point.
