### ISSUE TITLE
MediaType */* is incorrectly not considered as valid for JSON output

### ISSUE THREAD

**Issue by tadhgpearson** [FasterXML/jackson-jaxrs-providers#59]
I'm using the JacksonJsonProvider as part of Resteasy to build JSON-based APIs. When a standard error occurs, eg. HTTP 404, I would like to provide an error response in JSON. Thus I implemented an ExceptionMapper that produces output of type application/json.

However, in this case, when Resteasy submits a media type to the provider, it submits type `*/*`.
JSON should be considered a valid response format to this media-type request, however, we see that JacksonJsonProvider.hasMatchingMediaType() will respond false to this request when it should respond true. The result is that Resteasy cannot write error output and thus incorrectly generates an error 500.

**Comment by ntkoopman** [comment]
This happens on CXF with 2.5.0-rc1 as well. In my case when I throw an exception from a ContainerRequestFilter that is handled by an ExceptionMapper.

**Comment by cowtowncoder** [comment]
No work done on this, so it should behave just like 2.4.x

**Comment by tadhgpearson** [comment]
Yeah, I had good intentions to fix this, but then I found it was closer to the 'happy path'  for Resteasy to just add a new serialization provider for this case and avoids this issue entirely.

Here's the gist of what I did - JSON_PROVIDER is my current standard serialization configuration which exists in the same package

https://gist.github.com/tadhgpearson/a8d519ccf1d3599ecea3

**Comment by cowtowncoder** [comment]
Unfortunately I can not reproduce at this point; may be reopened with a reproducible test case or equivalent.
