### ISSUE TITLE
java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.util.BeanUtil.okNameForSetter since 2.6.0

### ISSUE THREAD

**Issue by ascheman** [FasterXML/jackson-jaxrs-providers#74]
Since release 2.6.0 of jackson-jaxrs-json-provider we see the following error when accessing a REST API:
```
org.eclipse.jetty.servlet.ServletHandler - 
javax.servlet.ServletException: org.glassfish.jersey.server.ContainerException: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.util.BeanUtil.okNameForSetter(Lcom/fasterxml/jackson/databind/introspect/AnnotatedMethod;Z)Ljava/lang/String;
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:397) ~[jersey-container-servlet-core-2.14.jar:na]
...
```
The error occurs in https://github.com/dukecon/dukecon_server (a very simple Spring-Boot RESTful service):
- Just clone the latest version (or even this commit: 0e5a31a76e910f09ce5cc951100b3172e83e179c)
- Change the property `<fasterxml.version>` in api/pom.xml to 2.6.0 or 2.6.1
- Build the parent project: mvn clean install
- Run the spring-boot application: cd impl && mvn spring-boot:run
- Get the /rest/talks resource: curl http://localhost:8080/rest/talks
- Check out the error in the log output or logfile: less logs/dukecon.log

**Comment by cowtowncoder** [comment]
I'm sorry but this exception suggest incompatibility between versions that container has been compiled with, and one it is deployed with. Otherwise you would see a compiler warning of the problem.
Minor versions of jackson core components and JAX-RS provider must match.

**Comment by ascheman** [comment]
Seems you are right spring-boot:1.2.5.Release (current as of today) depends on jackson core 2.4.6 which is also a dependency of jackson-jaxrs-json-provider 2.5.4 ... Thx!

**Comment by cowtowncoder** [comment]
@ascheman Glad you figured out where it comes from!

**Comment by ahzamfarhan** [comment]
Thanks aschman. your suggestion solved my problem. I changed faster xml version to 2.6.0

**Comment by cowtowncoder** [comment]
@ascheman good that 2.6 resolves the issue! Just one suggestion: please do not use `2.6.0` instead of latest patch version: instead, if you need that minor version, use `2.6.7`.
There is rarely a reason not to use the latest patch as there are dozens of fixes in patches.

**Comment by yunuskazan81** [comment]
Thanks man, you saved me.
