### ISSUE TITLE
Add YAMLMediaTypes file

### ISSUE THREAD

**Issue by HenrikHL** [FasterXML/jackson-jaxrs-providers#75]
It would be nice to have a YAMLMediaTypes.java file (in the jackson-jaxrs-yaml-provider-2.6.2.jar) just like SmileMediaTypes and CBORMediaTypes in their respective providers.

**Comment by cowtowncoder** [comment]
Makes sense to me, good idea.

One complication / open question is whether to include multiple possible media types; and if there is "primary" one or not.
As per:

http://stackoverflow.com/questions/332129/yaml-mime-type

there seems to be a fair bit of confusion for the best type to use. Granted, those answers are old.
But I haven't been able to find better answers so far.

**Comment by HenrikHL** [comment]
In the JacksonJaxbYAMLProvider.java line 25+26 looks like this:

@Consumes({"text/yaml", "application/yaml"})
@Produces({"text/yaml", "application/yaml"})

I propose adding multiple MediaTypes. These two lines should refer to the YMLMediaTypes.java file.

public class YAMLMediaTypes {
    public static final String    APPLICATION_JACKSON_YAML      = "application/yaml";
    public static final MediaType APPLICATION_JACKSON_YAML_TYPE = MediaType.valueOf(APPLICATION_JACKSON_YAML);
    public static final String    TEXT_JACKSON_YAML      = "text/yaml";
    public static final MediaType TEXT_JACKSON_YAML_TYPE = MediaType.valueOf(TEXT_JACKSON_YAML);
}

**Comment by cowtowncoder** [comment]
Implemented as suggested.
