### ISSUE TITLE
Non-JSON providers don't support custom MIME types with extensions

### ISSUE THREAD

**Issue by kleinsch** [FasterXML/jackson-jaxrs-providers#80]
The JSON provider supports things like `application/vnd.com.example.v1+json` but none of the other providers do. Their `hasMatchingMediaType` method defines support for those extensions, but the `@Consumes` and `@Produces` annotations are not wildcard, so `hasMatchingMediaType` never runs.

**Comment by cowtowncoder** [comment]
Actually, since this is just extending what JSON already this, it might be fine to include for 2.7.4.
Otherwise I'd be tempted to wait until 2.8. I'll have another look at the patch to make sure.
