### ISSUE TITLE
Ability to use Jackson types as query parameters

### ISSUE THREAD

**Issue by cowwoc** [FasterXML/jackson-jaxrs-providers#83]
Please provide code similar to https://github.com/mgajdos/jersey-param-converters/blob/master/src/main/java/sk/dejavu/blog/examples/paramconverters/provider/JacksonJsonParamConverterProvider.java that would enable us to receive types known by Jackson as JAX-RS query parameters. For example, I expect to be able to declare a `LocalDateTime` query parameter on my JAX-RS resource.

**Comment by cowwoc** [comment]
Nevermind, I misunderstood what that codebase goes. I was hoping that bridging Jackson and Jersey would allow me to use ISO8601 dates as query parameters, but I now understand that Jackson is expecting ISO8601 inside JSON objects, as opposed to ISO8601 directly.

**Comment by cowtowncoder** [comment]
Actually Jackson itself would not have any trouble deserializing date/time values from simple JSON String tokens. However as is this project does not cover any query parameter handling, at this point.
Whether there should be a set of add-ons to support those is a separate question, and I can't really say; I think Jersey and other JAX-RS impls provide a set of standard converters.
