### ISSUE TITLE
Include MediaType into AnnotationBundleKey used in ProviderBase 

### ISSUE THREAD

**Issue by NicoNes** [FasterXML/jackson-jaxrs-providers#85]
Hi,

Let's consider following jaxrs Application where two ContextResolver<ObjectMapper> are registered, one for application/javascript and another for application/json:

```java
@ApplicationPath("/")
	public static class MyApplication extends Application {

		@Provider
		@Produces("application/javascript")
		public static class JavascriptObjectMapperResolver implements ContextResolver<ObjectMapper> {

			private final ObjectMapper objectMapper;

			public JavascriptObjectMapperResolver() {
				this.objectMapper = new ObjectMapper().setSerializationInclusion(Include.NON_NULL)
						.setSerializationInclusion(Include.NON_EMPTY)
						.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)
						.configure(SerializationFeature.FAIL_ON_EMPTY_BEANS, false);
			}

			@Override
			public ObjectMapper getContext(Class<?> type) {
				return this.objectMapper;
			}

		}

		@Provider
		@Produces("application/json")
		public static class JsonObjectMapperResolver implements ContextResolver<ObjectMapper> {

			private final ObjectMapper objectMapper;

			public JsonObjectMapperResolver() {
				this.objectMapper = new ObjectMapper().setDateFormat(new StdDateFormat(TimeZone.getDefault(), Locale
						.getDefault()));
			}

			@Override
			public ObjectMapper getContext(Class<?> type) {
				return this.objectMapper;
			}

		}

		@Override
		public Set<Class<?>> getClasses() {
			return new HashSet<Class<?>>(Arrays.asList(MyResource.class, JacksonJaxbJsonProvider.class,
					JavascriptObjectMapperResolver.class, JsonObjectMapperResolver.class));
		}

	}
```

First call with "application/json" accept header => OK the JsonObjectMapperResolver is used
Second call with "application/javascript" accept header => KO the JavascriptObjectMapperResolver is not used because AnnotationBundleKey does not take MediaType into account

Do you understand my point ? 

Thank you

-Nicolas

**Comment by cowtowncoder** [comment]
I am not sure if this is something easily and reliably supportable because while I can see that you may want to have differently configured mappers for variations of JSON, for most users these two mime types should have same settings, and would not have to register separate mappers. Similarly mime types declared in `@Provider` may be wild cards, and it is not clear how key matching should then work, and/or whether desired behavior may be supported efficiently.

One thing that could perhaps work would be to add a configuration setting to allow use of either custom keys (subtypes of current one, or perhaps new interface). I would be open to adding a mechanism that would allow you to customize this, even if not changing the default behavior.

**Comment by NicoNes** [comment]
Hi,

Thank you for answering me. Yes you re right it is not a common behaviour and I understand that key caching could be tricky with wildcard.
Adding a configuration setting to allow the use of custom key will not really fix the issue. It will just move it to the user side since he will still have to deal with the wildcard key caching issue.

Actually I think the issue is more global and is about the way Jackson use ContextResolver. I opened another issue about that https://github.com/FasterXML/jackson-jaxrs-providers/issues/86.
In a few words ContextResolver are the mechanism provided by JAXRS to let user provides context information to a provider regarding a Mediatype ('@Produce') and a class type ('getContext(Class<?> type)'). So when provided by user it should be called first and its result not cached by the provider. 
I think this will solve our problem and add consitency in the use of ContextResolver between Jersey (jaxb xml feature) and Jackson.

**Comment by cowtowncoder** [comment]
From my perspective, moving responsibility from provider to user code would exactly solve the problem, in that something that was not possible becomes possible. It does not make it simple or trivial, but I have found that users tend to be good at solving problems that are specific to their use cases.
But I'll continue discussion in the other issue.
