### ISSUE TITLE
ContextResolver<ObjectMapper> must be called first when provided

### ISSUE THREAD

**Issue by NicoNes** [FasterXML/jackson-jaxrs-providers#86]
Hi,
Let's consider following code: 

	public static void main(String[] args) {

		ObjectMapper objectMapper = new ObjectMapper().setDateFormat(new StdDateFormat(TimeZone.getDefault(), Locale
				.getDefault()));
		javax.ws.rs.client.Client client = ClientBuilder.newClient().register(
				new JacksonJaxbJsonProvider(objectMapper, JacksonJaxbJsonProvider.DEFAULT_ANNOTATIONS));
		try {
		client.target("http://www.myendpoint.com/").request(MediaType.APPLICATION_JSON_TYPE);
		client.target("http://www.myendpoint.com/").register(new ContextResolver<ObjectMapper>() {
			@Override
			public ObjectMapper getContext(Class<?> type) {
				return new ObjectMapper().setSerializationInclusion(Include.NON_NULL)
						.setSerializationInclusion(Include.NON_EMPTY)
						.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)
						.configure(SerializationFeature.FAIL_ON_EMPTY_BEANS, false);
			}
		}).request(MediaType.APPLICATION_JSON_TYPE);
		} finally {
			client.close();
		}

- On the first request no ContextResolver<ObjectMapper> registered the objectMapper instance will be used => OK
- On the second request a ContextResolver<ObjectMapper> has been registered by the user  to provides context information to the provider but it is not used by the JacksonJaxbJsonProvider because of the cache. And even without the cache it would not have been used because `locateMapper()` first use `_mapperConfig.getConfiguredMapper()` instead of `_locateMapperViaProvider(type, mediaType)`

According to the JAXRs spec the goal of ContextResolver<ObjectMapper>is to let user provides context information to a provider. So if registered by user it must be called and taken into account by the provider.
Doing that it's up to the user implementing its own ContextResolver<ObjectMapper> to implement cache mechanism for ObjectMapper instance it will return. The JacksonJaxbJsonProvider should not cache anything from user ContextResolver.
Cache from JacksonJaxbJsonProvider should be use only if there is no ContextResolver<ObjectMapper>.

As an example please refer to the way Jersey hanlde the case for JAXBContext in `org.glassfish.jersey.jaxb.internal.AbstractJaxbProvider.getJAXBContext(Class type, MediaType mt)`.

What do you think ?

Thank you

-Nicolas

**Comment by cowtowncoder** [comment]
If the suggestion would be make provider always do a lookup via context resolver to find `ObjectMapper`, I would be worried about significant overhead, without much benefit for common usage case. I realize that the example above is just for purposes of illustration, but construction of new ObjectMapper for each call is very inefficient and something I would not suggest for real usage.

Then again, correctness trumps performance. My concern about JAXB, in general, is that it tends to require dynamic lookups in many cases where this would not seem to be needed, but tend to add significant lookup overhead -- in performance benchmarking overhead by dispatching tends to be bigger than serialization/deserialization. So adding more dynamic dispatching is one of the things I really would like to avoid if at all possible; especially since these lookups seem to do much more work than I would expect (based on time it takes).

But maybe a better question here is this: do you have specific place in existing code that you think should be changed?

**Comment by NicoNes** [comment]
Humm performance vs correctness... not easy.

I can understand the concern about performance but I also think that my point about consistency in the way ContextResolver is used is justified. I mean that  you choose to let users use ContextResolver to provide custom objectMapper so it must be done the way ContextResolver is supposed to work. In most cases, you're right, users will not register any ContextResolver but what happen if they do ?

Let's consider the code in the example. If I want to provide custom ObjectMapper how can I do ?
I can't register a new JacksonJaxbJsonProvider with the objectMapper since the provider has already been registered on the parent client and is inherithed by the WebTarget instance.
My only option would be to build another client to make such call. But Client are heavy-weight object whose instanciation should be restricted to small number. And I don't think it's the way Jaxrs client API should work according to the doc.

I don't know what to say, both Jersey and RestEasy always do a lookup first via context resolver for their JaxbProvider. It's the way the spec seem's to be so doing it in Jackson will just be the basic application of the spec.
However this does not prevent from opening a Jira  in Jersey and others JAXRS impl about the poor performance of lookup.

I'm really frustrated because I have no fifty-fifty solution.

At lower cost on things that can be done is : 

	@Override
	public ObjectMapper locateMapper(Class<?> type, MediaType mediaType) {
		// First: try to get configured one via context
		ObjectMapper objectMapper = _locateMapperViaProvider(type, mediaType);
		if (objectMapper == null) {
			// Then: were we configured with a specific instance?
			objectMapper = this._mapperConfig.getConfiguredMapper();
			if (objectMapper == null) {
				// If not, let's get the fallback default instance
				objectMapper = this._mapperConfig.getDefaultMapper();
			}
		}
		return objectMapper;
	}

But the ultimate solution will be the one in the attached file.
[ExtendedJacksonJaxbJsonProvider.txt](https://github.com/FasterXML/jackson-jaxrs-providers/files/335998/ExtendedJacksonJaxbJsonProvider.txt)

**Comment by cowtowncoder** [comment]
One thing that could help here would be having some estimate of efficiency of the extra lookup for `ObjectMapper` via provider. I honestly don't know how much overhead that particular call does, compared to all other introspection JAX-RS providers do for endpoint. If that is low enough I don't think I would mind, esp. since code included would otherwise fall back to the current cached access.

Also: minor refactoring that would easily allow inheritance based overrides (if not currently possible) I would gladly merge as the first step.

**Comment by cowtowncoder** [comment]
@NicoNes  Ok, not sure if this is sufficient, but I hope it's close and/or provides base to extend from.
I added 3 new `JaxRSFeature`s:

* `DYNAMIC_OBJECT_MAPPER_LOOKUP` (default: false)
* `CACHE_ENDPOINT_READERS` (default: true)
* `CACHE_ENDPOINT_WRITERS` (default: true)

changing of which should give you the behavior (minus bugs I may have added inadvertently).

First feature determines order of lookups in `locateMapper()`, and the other 2 control whether endpoint objects are cached or not; you'll want to disable caching, and enable fully dynamic lookup.

Let me know if this helps, and if so, works -- I am hoping to wrap up 2.8.0 release and this would be good to straighten out.

**Comment by NicoNes** [comment]
Hi,

Seems great :+1: 
I'll play with it and also try to benchmark static vs dynamic lookup to estimate the overhead. I'll let you now.
And aside from the cost of the dynamic lookup via provider,  do you have any idea of the estimate cost of calling _configForReading (or _configForWriting) each time ?

**Comment by cowtowncoder** [comment]
@NicoNes sounds good. As of now these being features that need to be changed, I am not worried about baseline performance, but it'd be good to have some idea of course.

As to `_configForReading`, bit hard to say. Creation and feature-enable/disable of `ObjectReader` (and `ObjectWriter` for the other one) is relatively cheap. Iterating over annotations may be slightly more costly, but nothing too drastic. Biggest cost would really be constructing new `ObjectMapper` (and thereby all serializers/deserializers), most other things are relatively cheap.
But it is all relative to cost of reading/writing itself, so for small payloads more significant than larger (stating the obvious here).
