### ISSUE TITLE
Can't use JacksonXMLProvider by default with Apache CXF

### ISSUE THREAD

**Issue by ilgrosso** [FasterXML/jackson-jaxrs-providers#88]
Due to [these annotations](https://github.com/FasterXML/jackson-jaxrs-providers/blob/master/xml/src/main/java/com/fasterxml/jackson/jaxrs/xml/JacksonXMLProvider.java#L48-L49), Apache CXF JAX-RS engine does not pick up `JacksonXMLProvider` correctly for `application/xml`.

If I subclass the original provider and put the [same annotations it used to have in previous versions](https://github.com/FasterXML/jackson-jaxrs-xml-provider/blob/master/src/main/java/com/fasterxml/jackson/jaxrs/xml/JacksonXMLProvider.java#L56-L57) instead, everything works fine.

Any special reason for keeping up with wildcards instead of specialized mime type? The comment

```
NOTE: required to support "non-standard" JSON variants
```

sounds a bit odd in that context.

Thanks!

**Comment by cowtowncoder** [comment]
@ilgrosso please discuss these on either `jackson-user` or `jackson-dev` mailing lists: issues are unfortunately not a very good mechanism for debating proper behavior or settings.

As to the comment: it just indicates that a few issues were reported about various widely (enough) used JSON mime types not being supported, and as a result change there was no good way to limit applicability.
Comment's wording could definitely be improved as it's not necessarily about content being non-JSON, but rather that it is application of JSON, encoded as new mime type; common problem with MIMe typing it seems (that is; it sometimes is about data format; other times not, and developers try to encode too much information into what is such a simple string).

At this point I would suggest that Apache CXF sub-classes providers and ensures annotations that work best for them are used. While ideally there would be no need, I think this would give more control to framework authors/maintainers, and help provide more stability.

**Comment by ilgrosso** [comment]
> issues are unfortunately not a very good mechanism for debating proper behavior or settings

Definitely agree: I couldn't find references for the two Google Groups above, hence I've opened this issue.
I have subscribed to `jackson-user@googlegroups.com`, for future questions, anyway.

> At this point I would suggest that Apache CXF sub-classes providers and ensures annotations that work best for them are used. While ideally there would be no need, I think this would give more control to framework authors/maintainers, and help provide more stability.

Possibly not the best solution for a JAX-RS provider which is supposed to be standard, but easy enough to implement anyway.

Thanks for feedback!

**Comment by cowtowncoder** [comment]
Agreed that ideally fully standard one would be used. But based on my experiences, JAX-RS spec, implementations and the resulting system is quite complicated and unfortunately finding fully one-size-fits-all solution for provider seems very difficult.
