### ISSUE TITLE
Requiring JAX-RS 2.0 has knock-on effects

### ISSUE THREAD

**Issue by mcdee** [FasterXML/jackson-jaxrs-providers#90]
Issue #82 has caused problems where Jackson can no longer be used with Jersey 1.x.  Although Jersey 2.x is the current version 1.x is still very widely used.  Could this change be considered for reversion?

**Comment by cowtowncoder** [comment]
@mcdee This change was discussed on mailing list and there were no objections, so I don't think we would like reversion, at least not without further discussion.
Does code actually work if overriding Maven (or whatever build system you use) dependencies?
I do not remember if there are explicit references to JAX-RS 2 types.

Another angle here is that 2.7 is still JAX-RS 1.x compatible, and at some point we do need to move to JAX-RS 2.

**Comment by mcdee** [comment]
At the least there is a reference to NoContentException at https://github.com/FasterXML/jackson-jaxrs-providers/blob/5312811bcc6dbe54fb7175b9a00a3e98a1535a83/base/src/main/java/com/fasterxml/jackson/jaxrs/base/ProviderBase.java#L972 so we can't just fall back to an earlier version.

I'm using 2.7.7 for now.

**Comment by sappenin** [comment]
I'm also having this problem.  If I upgrade to 2.8.x, I get a java.lang.NoClassDefFoundError for  NoContentException.  I'm using 2.7.7 for now as well.

**Comment by cowtowncoder** [comment]
@sappenin That would mean that you are trying to run on JAX-RS 1.x container (or perhaps have duplicate jars in classpath, including one for 1.x)

**Comment by sappenin** [comment]
@cowtowncoder Yes, exactly - I'm running Jersey 1.19.x/JAX-RS 1.1.

**Comment by DigitalSmile** [comment]
I think, there should be definitely an option to use JAX-RS 1.x It is widely spread and I cannot see any reason why Jackson should be locked on JAX-RS 2.x only.

**Comment by cowtowncoder** [comment]
This was discussed on dev list, and decision was made. If Jersey 1.x compatibility is needed, please use Jackson 2.7. If you do not like this, please bring it up on mailing lists; these issues are not debated or decided on issue tracker.

I will leave this issue open in case others find it, but there will be no action without significant re-evaluation by developers.

**Comment by DigitalSmile** [comment]
Thanks, for pointing it out.
I suppose I have found a thread, just leave the link here for next newcomers
https://groups.google.com/forum/#!topic/jackson-dev/-aGMJoV4R2U

**Comment by cowtowncoder** [comment]
Thanks! Good idea to add the link too.

**Comment by Spikhalskiy** [comment]
Absence of NoContentException is not the only problem
```
public class JaxRsApplication extends javax.ws.rs.core.Application {
    @Override
    public Set<Class<?>> getClasses() {
        final Set<Class<?>> classes = new HashSet<>();
        classes.add(com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider.class);
        return classes;
    }
}
```
Not picking up properly by Jersey 1.x with Jackson 2.8
For sure I'm for continuing support of first major JaxRS and Jersey versions, migration would be painfull for many projects and they would stuck with 2.7 branch.

**Comment by cowtowncoder** [comment]
It is possible to change accessing of `NoContentException` to use reflection and work with 1.x, but I would like to know what else is triggering problems.

**Comment by Spikhalskiy** [comment]
2.8.5 release works fine for me with Jersey 1.x, NoContentException fix was enough, at least for my usage.

**Comment by cowtowncoder** [comment]
@Spikhalskiy excellent, thank you for verifying this.

**Comment by cowtowncoder** [comment]
Fixed via #91

**Comment by alexandru-2016** [comment]
I am using Jackson 2.8.1 and Jersey 1.18.6, and am getting NoClassDefFoundError: javax/ws/rs/core/NoContentException

**Comment by Spikhalskiy** [comment]
@alexandru-2016 it was fixed in 2.8.5 as you can see above.

**Comment by sonnyhcl** [comment]
The workaround code is removed in jackson 2.13 with this commit. Is there any other way to workaround with jersey 1.x for legacy users?
- [Fix #134 (remove JAX-RS 1.x compatibility work-around) · FasterXML/jackson-jaxrs-providers@f58c631](https://github.com/FasterXML/jackson-jaxrs-providers/commit/f58c63162064e9c4d58ceac478a912d87a89d808)

**Comment by cowtowncoder** [comment]
Version 2.13 did drop JAX-RS 1.x compatibility so Jersey 1.x legacy users should keep using version 2.12; latest patch being 2.12.6.

**Comment by pjfanning** [comment]
@dcleao do you think having just the NoContentException class in its own jar is enough? If it is that is a nice approach. https://github.com/FasterXML/jackson-jaxrs-providers/commit/f58c63162064e9c4d58ceac478a912d87a89d808 has had a massive impact on Hadoop users and all the Big Data tooling that needs to support Hadoop.

**Comment by dcleao** [comment]
@pjfanning the class itself has no other dependencies.

For FasterXML, I believe I read somewhere that this was a matter of simplifying their code-based, while still _somewhat_ supporting both Jax-RS versions?

I can only state this is working in my case...

@cowtowncoder could you shed some light on if this is a feasible solution, or if hidden problems are likely to arise? Thank you.

**Comment by cowtowncoder** [comment]
I think @pjfanning 's project sounds like a good solution. FasterXML JAX-RS provider has moved on from Jersey 1.0 and trying to get support back in would be  confusing and painful (including but not limited to clashes between JAX-RS 1.0 / 2.0 classes).
