### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by Erhannis** [FasterXML/jackson-jaxrs-providers#95]
When I clone the repo, check out one of the release tags/branches (such as branch 2.8, tag jackson-jaxrs-providers-2.7.8, tag jackson-jaxrs-providers-2.5.4), and run mvn clean package, it fails tests in the JSON module:

Failed tests:
  WriteModificationsTest>WriteModificationsTestBase.testIndentationWithResource:170 expected:<{[
  "x" : 1,
  "y" : 2]
}> but was:<{[
  "x" : 1,
] "y" : 2
}>
  WriteModificationsTest>WriteModificationsTestBase.testIndentationWithFilter:147 expected:<{[
  "x" : 1,
  "y" : 2]
}> but was:<{[
  "x" : 1,
] "y" : 2
}>

**Comment by Erhannis** [comment]
Further info: it looks like these tests were introduced between 2.2.3 and 2.3.0, and have apparently never passed.

**Comment by cowtowncoder** [comment]
Odd; all tests pass for me. I am guessing this could be due to some platform/OS dependant thing in tests, such as relying on certain ordering of properties (this depends on JDK providing methods/fields in specific static order).

Thank you for reporting this.

**Comment by cowtowncoder** [comment]
Can not reproduce, does not occur at Travis, so not sure what could be done here.
