### ISSUE TITLE
ParamConverterProvider implementations for Date/Time classes

### ISSUE THREAD

**Issue by cowwoc** [FasterXML/jackson-jaxrs-providers#96]
(Copied from https://github.com/FasterXML/jackson-modules-java8/issues/7)

Please provide `ParamConverterProvider` implementations for all date/time types that make sense to use as query parameters. For example, here is an implementation I used to pass `LocalDateTime` as a query parameter (feel free to use it):

```
/**
 * Enables LocalDateTime to be used as a QueryParam.
 *
 * @author Gili Tzabari
 */
@Provider
@Singleton
public class LocalDateTimeConverter implements ParamConverterProvider {
    @Override public <T> ParamConverter<T> getConverter(Class<T> rawType, Type genericType, Annotation[] annotations) {

        if (!rawType.isAssignableFrom(LocalDateTime.class)) {
            return null;
        }
        return new ParamConverter<T>() {
            @Override
            @SuppressWarnings("unchecked")
            public T fromString(final String value) {
                if (value == null) {
                    throw new IllegalArgumentException("value may not be null");
                }
                return (T) LocalDateTime.parse(value);
            }

            @Override
            public String toString(final T value) {
                return ((LocalDateTime) value).format(DateTimeFormatter.ISO_LOCAL_DATE_TIME);
            }
        };
    }
}
```

**Comment by cowtowncoder** [comment]
Also just realized that there are some subtleties wrt where to locate this (project-wise), due to dependency to Java 8.

But one thing I am wondering is this: since nothing in above relies on Jackson, does this even make sense here? Ideally various configuration settings would be used, but unless there is some way to access `ObjectMapper` or `ObjectReader`, that can't be done. So in a way maybe this would belong more to DropWizard project?

**Comment by cowwoc** [comment]
Good point, and in retrospect it seems I caught this in the past but forgot about it :) https://github.com/dropwizard/dropwizard-java8/issues/26

Closing this issue.

**Comment by cowtowncoder** [comment]
@cowwoc ok no problem. Took a while for me to figure it out too.
