### ISSUE TITLE
Extend version range to allow usage with jax-rs 2.1

### ISSUE THREAD

**Issue by cschneider** [FasterXML/jackson-jaxrs-providers#97]
CXF 3.2.0-SNAPSHOT installs the jax-rs 2.1 spec bundles in OSGi. Unfortunately jackson jaxrs is not allowing this spec version in its imports.

We use this artifact for the jax rs spec:
org.apache.servicemix.specs : org.apache.servicemix.specs.jsr370-api-m1 : 2.8-SNAPSHOT

So it is necessary to extend the version range to include jax rs 2.1. I will create a PR.
As far as I know the spec is fully backwards compatible. So I expect no issues with jackson.

In the current version range which excludes 2.1.0 it does not install at all in  apache karaf.

**Comment by cowtowncoder** [comment]
Included in 2.9.0, 2.8.10.
